### ISSUE TITLE
Create a sourcemap for the production bundle

### ISSUE THREAD

**Issue by gdrouet** [my3D-Team/js-html-kanban#2]
Debugging the bundle is possible only if we have its sourcemap. The current way browserify and ugilifyjs are used does not produce a sourcemap. This should be fixed (the sourcemap should be an external file):
- https://github.com/substack/node-browserify#external-source-maps
- https://github.com/mishoo/UglifyJS2#usage

**Comment by NathanDM** [comment]
DONE with exorcist :)
